%% Audio Recorder
%  Written by Haomiao
%  DEC, 2012

function audioProcessor()
%% Clean-up current workspace
clear; clc;

tmp = findobj('Tag','hjiang_audioWindow');
if ~isempty(tmp), close(tmp); end

%% Plot GUI
hG.fig     = figure;
fig_pos    = get(hG.fig,'Position');
fig_width  = 800;
fig_height = 600;

%% Initialize Data
hG.recorder = audiorecorder;

% Set window name and position
set(hG.fig,...
    'Tag', 'hjiang_audioWindow',...
    'NumberTitle','Off',...
    'Resize','Off',...
    'Position',[fig_pos(1)-200,fig_pos(2)-300,fig_width,fig_height],...
    'Name','Small Software - Music Processing'...
    );

% Hide menu bar
set(hG.fig, 'menubar', 'none');


%% Draw Panels
% Draw main panel
hG.main = uipanel(... % Main panel
    'Parent',hG.fig,...
    'Position', [0.005 0.01 0.99 0.89],...
    'BackgroundColor',get(gcf,'Color')...
    );

% Draw recoder control panel
hG.control = uipanel(... % Record Control panel
    'Parent',hG.fig,...
    'Position',[0.005 0.90 0.245 0.09],...
    'BackgroundColor',get(gcf,'Color'),...
    'Title', 'Recorder'...
    );

% Draw Music Loading Panel
hG.musicLoad = uipanel(... % Music Load Panel
    'Parent', hG.fig,...
    'Position', [0.255 0.90 0.74 0.09],...
    'BackgroundColor', get(gcf,'Color'),...
    'Title', 'Music Processor'...
    );

%% Draw audio recording control buttons
% Draw Start Recording Button
hG.startRecord = uicontrol(... % Start Record Button
    'Parent', hG.control, ...
    'Style', 'PushButton', ...
    'Units', 'Normalized', ...
    'Position', [0.04 0.1 0.2 0.8],...
    'String', 'Start',...
    'HorizontalAlignment','Center',...
    'Callback',@startRecordCallback ...
    );

% Draw Stop Button
hG.stopRecord = uicontrol(... % Stop Record Button
    'Parent', hG.control, ...
    'Style', 'PushButton', ...
    'Units', 'Normalized', ...
    'Position', [0.28 0.1 0.2 0.8],...
    'String', 'Stop',...
    'HorizontalAlignment','Center',...
    'Callback',@stopRecordCallback ...
    );

% Draw Pause / Resume Button
hG.pauseResume = uicontrol(... % Pause / Resume Button
    'Parent', hG.control,...
    'Style', 'PushButton',...
    'Units', 'Normalized',...
    'Position', [0.52 0.1 0.2 0.8],...
    'String', 'Pause',...
    'HorizontalAlignment','Center',...
    'Callback', @pauseResumeCallback...
    );
    
% Draw Play Button
hG.playRecord = uicontrol(...
    'Parent', hG.control, ...
    'Style', 'PushButton', ...
    'Units', 'Normalized', ...
    'Position', [0.76 0.1 0.2 0.8],...
    'String', 'Play',...
    'HorizontalAlignment','Center',...
    'Callback',@playRecordCallback ...
    );

%% Draw Music Loading & Processing Buttons
%  Draw music file path text box
hG.musicPath = uicontrol(...
    'Parent', hG.musicLoad, ...
    'Style' , 'text',...
    'Units' , 'Normalized',...
    'Position', [0.04 0.3 0.3 0.4],...
    'HorizontalAlignment', 'Left',...
    'String', '',...
    'BackgroundColor',get(gcf,'Color')-0.1,...
    'Enable', 'inactive' ...
    );

% Draw music load button
hG.loadMusic = uicontrol(...
    'Parent', hG.musicLoad, ...
    'Style' , 'PushButton', ...
    'Units' , 'Normalized', ...
    'Position', [0.38 0.2 0.2 0.6], ...
    'String', 'Select Music', ...
    'Callback', @loadMusicCallback ...
    );

% Draw music process button
hG.processMusic = uicontrol(...
    'Parent', hG.musicLoad, ...
    'Style' , 'PushButton', ...
    'Units' , 'Normalized', ...
    'Position', [0.62 0.2 0.15 0.6],...
    'String', 'Process', ...
    'Callback', @processMusicCallback, ...
    'Enable', 'off'...
    );

% Draw play music button
hG.playMusic = uicontrol(...
    'Parent', hG.musicLoad, ...
    'Style' , 'PushButton', ...
    'Units' , 'Normalized', ...
    'Position', [0.8 0.2 0.15 0.6], ...
    'String', 'Play', ...
    'Callback', @musicPlayCallback, ...
    'Enable', 'off'...
    );

%% Draw unmix Sound List
hG.unmixSound = uicontrol(...
    'Parent', hG.main, ...
    'Style' , 'listbox', ...
    'Units' , 'Normalized', ...
    'Position', [0.01 0.01 0.2 0.98] ...
    );


%% Save Data
setappdata(hG.fig,'handles',hG);

end

function startRecordCallback(~,~)
    hG.fig = findobj('Tag','hjiang_audioWindow');
    hG = getappdata(hG.fig,'handles');
    record(hG.recorder);
end

function stopRecordCallback(~,~)
    hG.fig = findobj('Tag','hjiang_audioWindow');
    hG = getappdata(hG.fig,'handles');
    stop(hG.recorder);
end

function playRecordCallback(~,~)
    hG.fig = findobj('Tag','hjiang_audioWindow');
    hG = getappdata(hG.fig,'handles');
    play(hG.recorder);
    pause(25);
end

function pauseResumeCallback(src,~)
    hG.fig = findobj('Tag','hjiang_audioWindow');
    hG = getappdata(hG.fig,'handles');
    str = get(src,'String');
    if (strcmp(str,'Resume'))
        resume(hG.recorder);
        set(src,'String','Pause');
    else
        pause(hG.recorder);
        set(src,'String','Resume');
    end
end

function loadMusicCallback(~,~)
    hG.fig = findobj('Tag','hjiang_audioWindow');
    hG = getappdata(hG.fig,'handles');
    
    [fileName, PathName] = uigetfile('*.wav','Select Music to Process');
    if fileName
        set(hG.musicPath,'String',[PathName fileName]);
        set(hG.processMusic, 'Enable', 'on');
        set(hG.playMusic, 'Enable',  'on');
    end
end

function musicPlayCallback(src,~)
    hG.fig = findobj('Tag','hjiang_audioWindow');
    hG = getappdata(hG.fig,'handles');
    str = get(src,'String');
    
    if (strcmp(str,'Play'))
        fileName = get(hG.musicPath,'String');
        try
            [audioData Fs] = wavread(fileName);
        catch err
            disp(err);
            return;
        end
        hG.musicPlayer = audioplayer(audioData,Fs);
        play(hG.musicPlayer);
        set(src,'String','Stop');
    else
        stop(hG.musicPlayer);
        set(src,'String','Play');
    end
    setappdata(hG.fig,'handles',hG);
end

function processMusicCallback(~,~)
    hG.fig = findobj('Tag','hjiang_audioWindow');
    hG = getappdata(hG.fig,'handles');
    
    fileName = get(hG.musicPath,'String');
    try
        [audioData,Fs] = wavread(fileName);
    catch err
        disp(err);
        return;
    end
    % Assume that mix source number is 2
    disp('Start Processing');
    mixN = 2;
    audioData = audioData(1:10e5,:);
    
    W=eye(mixN);
    anneal = [0.1 0.1 0.1 0.05 0.05 0.05 0.02 0.02 0.01 0.01 ...
            0.005 0.005 0.002 0.002 0.001 0.001]; 
    for iter=1:length(anneal)
        m = size(audioData, 1); 
        order = randperm(m); 
        for i = 1:m
            x = audioData(order(i), :)';
            g = 1 ./ (1 + exp(-W * x));
            W = W + anneal(iter) * ((1 - 2*g)*x' + inv(W'));
        end
        disp(['Iteration:' num2str(iter)]);
    end
    
    S = audioData * W';
    S=0.99 * S./(ones(size(mix,1),1)*max(abs(S)));
    
    wavwrite(S(:,1),Fs,16,'unmix1.wav');
    wavwrite(S(:,2),Fs,16,'unmix2.wav');
    
    set(hG.unmixSound, 'String',{'Unmix Soudn 1','Unmix Sound 2'});
    disp('Process Completed');
end